version: '3'

services:
  rapidpro:
    image: ${RAPIDPRO_IMAGE:-praekeltfoundation/rapidpro:latest}
    ports:
      - '8000:8000'
    environment:
      - DOMAIN_NAME=localhost
      - ALLOWED_HOSTS=*
      - TEMBA_HOST=localhost
      - DJANGO_DEBUG=off
      - DATABASE_URL={$RAPIDPRO_DB_URL:-postgresql://postgres:@10.200.10.1/rapidpro}
      - REDIS_URL=${RAPIDPRO_REDIS_URL:-redis://10.200.10.1:6379/0}
      - SECRET_KEY={$RAPIDPRO_SECRET_KEY:-super-secret-key}
      - MANAGEPY_COLLECTSTATIC=off
      - MANAGEPY_COMPRESS=off
      - MANAGEPY_INIT_DB=off
      - MANAGEPY_MIGRATE=off

  celery:
    image: ${RAPIDPRO_IMAGE:-praekeltfoundation/rapidpro:latest}
    depends_on:
      - rapidpro
    environment:
      - DATABASE_URL={$RAPIDPRO_DB_URL:-postgresql://postgres:@10.200.10.1/rapidpro}
      - REDIS_URL=${RAPIDPRO_REDIS_URL:-redis://10.200.10.1:6379/0}
      - SECRET_KEY={$RAPIDPRO_SECRET_KEY:-super-secret-key}
    command: ["/venv/bin/celery", "--beat", "--app=temba", "worker", "--loglevel=INFO", "--queues=celery,msgs,flows,handler"]

